version: '3.8'

services:
  investment_dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: equity_lens_v.1.7:invest_dashboard
    ports:
      - "${PORT:-8501}:80"  # Maps port 8501 on the host to port 80 in the container
      - "7813:80"           # Additional port mapping if needed
    env_file:
      - .env
    volumes:
      - .:/app  # Maps the project directory to the /app directory in the container
    environment:
      - MODEL_DIM=${MODEL_DIM}
      - NUM_HEADS=${NUM_HEADS}
      - NUM_LAYERS=${NUM_LAYERS}
      - OUTPUT_DIM=${OUTPUT_DIM}
      - LEARNING_RATE=${LEARNING_RATE}
      - NUM_EPOCHS=${NUM_EPOCHS}
      - BATCH_SIZE=${BATCH_SIZE}
      - RISK_FREE_RATE=${RISK_FREE_RATE}
      - DELTA=${DELTA}
      - TAU=${TAU}
      - SEQUENCE_LENGTH=${SEQUENCE_LENGTH}
      - BATCH_SIZE_SMP=${BATCH_SIZE_SMP}
      - EPOCHS=${EPOCHS}
      - LEARNING_RATE_SMP=${LEARNING_RATE_SMP}
    command: [ "streamlit", "run", "investment_dashboard/main.py" ]
